version: '3.8'

services:
  web:
    build: ./services/web
    # image: eduar2020/weblog:0.1
    container_name: web_weblog
    command: gunicorn --bind 0.0.0.0:5000 run:app
    expose:
      - 5000
    depends_on:
      - db
      
  db:
    image: postgres:13-alpine
    # image: eduar2020/psql:0.1
    container_name: psql_weblog
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=weblog
      - POSTGRES_PASSWORD=weblog
      - POSTGRES_DB=weblog_dev

  nginx:
    build: ./services/nginx
    container_name: nginx_weblog
    volumes:
      - static_volume:/weblog/services/web/weblog/static
    ports:
      - 5000:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume: