version: '3.8'

services:
  web:
    build: ./services/web
    command: gunicorn --bind 0.0.0.0:5000 run:app
    ports:
      - 5000:5000

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=weblog
      - POSTGRES_PASSWORD=weblog
      - POSTGRES_DB=weblog_dev

volumes:
  postgres_data: