version: '3.8'

services:
  web:
    build: ./services/web
    command: gunicorn --bind 0.0.0.0:8000 run:app
    ports:
      - 5000:8000

  nginx:
    build: ./services/nginx
    ports:
      - 5000:80
    depends_on:
      - web