apiVersion: apps/v1 # different components use different api version, so look it up.
kind: Deployment
metadata:
  name: postgres # deployment name
  namespace: dev
  labels:
    app: postgres # this label will be selected by Service
spec:
  replicas: 1
  selector: # find
    matchLabels:
      app: postgres
  template: # this configuration applies to a Pod
    metadata:
      labels:
        app: postgres # creates a key value pair  'app: mongodb' so that deployment can create a connection to the pod that matches with this pair
    spec: # blueprint of a pod
      containers:
        - name: postgres # container name
          env:
            - name: POSTGRES_USER
              value: weblog
            - name: POSTGRES_PASSWORD
              value: weblog
            - name: POSTGRES_DB
              value: weblog_dev
          image: postgres:13-alpine
          ports:
            - containerPort: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: dev
spec:
  selector:
    app: postgres # creates a connection between service and deployment or pods in deployment
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
