name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Flask Application Docker image
        with:
          context: ./services/web
        run: docker build . --file ./services/web/Dockerfile --tag eduar2020/weblog:$(date +%s)
