name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./services/web/
    steps:
      - uses: actions/checkout@v3
      - name: Build the Flask ApplicationDocker image
        run: docker build . --file ./services/web/Dockerfile --tag eduar2020/weblog:$(date +%s)
